### PR TITLE
codespaces - utilize PROMPT_DIRTRIM to clean up PROMPT

### LINKED ISSUE #808: Shorten very long working directories in codespaces PROMPT
Would be great to limit the max length of the path with some ellipsis when it gets too long. For example, replacing this path:
image
with
`/workspaces/../.../VMAgent.Local.Tests` (or similar)

A lot of oh my zsh themes do this (and i love it)

_Originally posted by @joshspicer in https://github.com/microsoft/vscode-dev-containers/pull/807#discussion_r607257026_

### PR DESCRIPTION
**Pull request by joshspicer**
Set `PROMPT_DIRTRIM` for the default codespaces prompt for a more tidy look.

See the `...` below.

image

closes #808

### CODE REVIEW

**Comment by jkeech** [comment]
The change looks good, but it's definitely a personal preference. Not sure which way we want to go here. I actually prefer the full path without trimming so I get more context on where I am within the folder structure without having to run extra commands like `pwd`, but I know a lot of people like the trimming.  @Chuxel, thoughts?

**Comment by joshspicer** [comment]
I think a middle group could be to bump up the `...` threshold from `2` to maybe `4` or `5` (although imo the smaller the better).

Here is another example, you can see the line itself needs to wrap because the path is so long (and this isn't even _that_ many layers deep!)

a

**Comment by Chuxel** [comment]
@joshspicer If you switch to `zsh` what happens?   I can't remember the logic that zsh implements in this scenario... I seem to recall you can pick whether you see truncated or full and I don't remember which it is using. Regardless, their patterns are very well tested in the wild since it's the gold standard for prompt customization so if we subset it would be good to line it up. Either way we'd want to line up both themes I think as well.

**Comment by joshspicer** [comment]
as expected `PROMPT_DIRTRIM` doesn't give it to use for free with `zsh`
image

**Comment by joshspicer** [comment]
maybe i'm missing something, but how do I open a `zsh` shell?  I've running `zsh` and changing the shell manually with `chsh`...  Regardless i'm just dropped back into a bash shell.

image

**Comment by Chuxel** [comment]
@joshspicer The theme is identical so you likely are in the zsh shell. :smile:

**Comment by joshspicer** [comment]
:D My `echo $SHELL` did not change so i'm not sure

**Comment by Chuxel** [comment]
@joshspicer A more foolproof way to tell is `echo $0`.  The SHELL doesn't always update particularly if it was set in image somewhere.

**Comment by joshspicer** [comment]
ah ha! 
image

**Comment by joshspicer** [comment]
For `zsh`, this is what I propose (previous commit):
image

**Comment by joshspicer** [comment]
image

@jkeech @Chuxel - How do we feel about a DIRTRIM at 4 layers deep (This screenshot is bash, I implemented a slightly different, but similar shortening in zsh in the previous commit)

**Comment by jkeech** [comment]
@joshspicer, four levels seems good to me 👍

**Comment by Chuxel** [comment]
LGTM as well!

**Pull request merged**
