### PR TITLE
Allow disable git status, drop omb stub, handle gid in different group name

### PR DESCRIPTION
**Pull request by Chuxel**
This PR resolves https://github.com/microsoft/vscode-dev-containers/issues/986 by allowing users to disable the git stauts part of the default prompt.  

It is modeled after Oh My Zsh!'s use of git config to handle this same situation so you can vary the behavior by repo and you do not need to update global env vars to change it. This also allows it to survive a "rebuild" if set for a repository.

To update:
```
git config codespaces-theme.hide-status 1
```

Or globally (e.g. from dotfiles):
```
git config --global codespaces-theme.hide-status 1
```

This works with both the bash and ZSH prompts, though OMZ has its own setting that also works.

I also: 

1. Removed the old "Oh My Bash" stub which was removed 9 months ago since enough time has passed.

2. Handled scenarios where the non-root user's default group is not the same as the username rather than hard coding it (this was a problem initally for the jupyter-datascience-notebook image).

### CODE REVIEW

**Review by joshspicer — APPROVED** [review]

**Comment by joshspicer** [comment]
This is great! We still don't want to close that linked issue though

**Comment by Chuxel** [comment]
@joshspicer In terms of leaving the issue open, are you thinking about maintaining visibility or going down the path of a broader fix?

**Comment by jacobwoffenden** [comment]
Hi @Chuxel,

I've been `script-library/common-debian.sh` in my devcontainer build, and I think this has introduced the following error

```
docker run -it --rm ghcr.io/maglevlabs/sre@sha256:54aa01385a51c83eb8dc005bb40b891cc562956dc2cfc6fdeb9237a386a09c20
zsh: parse error: condition expected: !=                                                                                                                                     
sre ➜ ~ $ 
```

Whereas the version directly before doesn't

```
docker run -it --rm ghcr.io/maglevlabs/sre@sha256:c18e9d5d6ad4b2b36d8cfaf66ed59156dea1a5825c0c25c876e900bb6a22a02b
sre ➜ ~ $ 
```

https://github.com/microsoft/vscode-dev-containers/commit/3e77cb2501905f1de5e6e0f3dea98f2a7a697425#diff-6cf07d9e0c4858db352327b79b45cfdad0e81ca06d0b7c358b3503da6a55768aR338-R339

**Comment by Chuxel** [comment]
@jacobwoffenden  Thanks. Should be resolved now.

**Comment by jacobwoffenden** [comment]
Yes, thanks @Chuxel! I'll stick to the released versions from now on

**Pull request merged**
