### PR TITLE
Add cmake-tools to default C++ container?

### PR DESCRIPTION
**Pull request by jureid**
@esweet431 - I'm wondering if we should add CMake Tools to VS Code's default C++ dev container. The Dockerfile installs cmake. @bobbrow - Do you know if we do this for Codespaces?

### CODE REVIEW

**Comment by bobbrow** [comment]
It makes sense to me.  I thought CodeSpaces included it, but if they use this container, perhaps my memory is wrong.

**Comment by esweet431** [comment]
Yeah, if we're installing cmake.exe then I agree it makes sense to install cmake-tools. I'm assuming the dockerfile already includes cpptools?

**Comment by esweet431** [comment]
> I'm assuming the dockerfile already includes cpptools?

Nvm sorry, I see it in the JSON

**Comment by jureid** [comment]
> It makes sense to me. I thought CodeSpaces included it, but if they use this container, perhaps my memory is wrong.

I also thought they included it but I can't find it in their configuration files: https://github.com/microsoft/vscode-dev-containers/tree/main/containers/codespaces-linux

Adding @Chuxel to review this PR. Also, Chuck, do you know if the default Codespace configuration includes cmake-tools?

**Review by Chuxel — APPROVED** [review]

**Pull request merged**
