### PR TITLE
Add Scala Community Devcontainer

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Comment by gliptak** [comment]
@Chuxel please review

**Comment by gliptak** [comment]
@joshspicer please review

**Comment by Tobrandalna** [comment]
> @Chuxel please review

Unsubscribe

**Comment by Tobrandalna** [comment]
container-templates/dockerfile/.devcontainer/devcontainer.json

**Pull request closed without merging**
