### PR TITLE
bump npm to latest v6

### PR DESCRIPTION
**Pull request by joshspicer**
Given our oryx upstream dependency, our npm version is lower than currently required.  Bumping it here by adding this line to the dockerfile

### CODE REVIEW

**Comment by Chuxel** [comment]
@joshspicer Looks like there's a path ordering issue with the recent updates to add `/home/codespace/.nodejs` into the `PATH`. `/home/codespace/.npm-global/bin/npm` needs to be before it.

I manually installed npm@6.14.14 and was stuck on the older version because of the path order:
```
/home/codespace/.nodejs/current/bin/npm
/home/codespace/.npm-global/bin/npm
/opt/nodejs/lts/bin/npm
```

**Comment by joshspicer** [comment]
I bumped `NPM_GLOBAL` up higher.  I don't see any reason to move other other `/home/codespace/.<platforms>` down - don't we always want those to take precedence

**Comment by Chuxel** [comment]
@joshspicer There's other problems here too. NVM is too late, so if you're non-interactive, you'd get the Oryx version (since there's no sourcing of nvm), ditto with PIPX, SDKMAN, etc.  Logically those paths are equivalent to `ORYX_PATHS` in the original list.

**Comment by joshspicer** [comment]
this is the new ordering of the path (for readability/review)

```
${NPM_GLOBAL}/bin
${ORIGINAL_PATH}
${NVM_DIR}/current/bin
${DOTNET_ROOT}
${DOTNET_ROOT}/tools
${SDKMAN_DIR}/bin
${SDKMAN_DIR}/candidates/gradle/current/bin
${SDKMAN_DIR}/candidates/java/current/bin
/opt/maven/lts
${CARGO_HOME}/bin
${GOROOT}/bin
${GOPATH}/bin
${PIPX_BIN_DIR}
/opt/conda/condabin
${JAVA_ROOT}/current/bin
${NODE_ROOT}/current/bin
${PHP_ROOT}/current/bin
${PYTHON_ROOT}/current/bin
${RUBY_ROOT}/current/bin
${MAVEN_ROOT}/current/bin
${HUGO_ROOT}/current/bin
${ORYX_PATHS}
```

**Comment by joshspicer** [comment]
Path ordering:

```
${NVM_DIR}/current/bin
${NPM_GLOBAL}/bin
${ORIGINAL_PATH}
${DOTNET_ROOT}
${DOTNET_ROOT}/tools
${SDKMAN_DIR}/bin
${SDKMAN_DIR}/candidates/gradle/current/bin
${SDKMAN_DIR}/candidates/java/current/bin
/opt/maven/lts
${CARGO_HOME}/bin
${GOROOT}/bin
${GOPATH}/bin
${PIPX_BIN_DIR}
/opt/conda/condabin
${JAVA_ROOT}/current/bin
${NODE_ROOT}/current/bin
${PHP_ROOT}/current/bin
${PYTHON_ROOT}/current/bin
${RUBY_ROOT}/current/bin
${MAVEN_ROOT}/current/bin
${HUGO_ROOT}/current/bin
${ORYX_PATHS}
```

**Review by Chuxel — APPROVED** [review]

**Comment by joshspicer** [comment]
image

**Pull request merged**
