### PR TITLE
Fix kubernete-helm certificates

### PR DESCRIPTION
**Pull request by Shikanime**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

Bugfix

## What is the current behavior?

Fixes: #33

## What is the new behavior?

Fix kubernetes-helm missing certificate.

## Does this PR introduce a breaking change?

No

### CODE REVIEW

**Comment by Chuxel** [comment]
@Shikanime Great catch!  Will review now.

**Comment by Chuxel** [comment]
@Shikanime Ok, so the problem here is that if you volume mount .minikube and you're not using minikube, the container fails to start.

```
Failed: Starting the development container
Command failed: C:\Program Files\Docker\Docker\Resources\bin\docker.exe run -a STDOUT -a STDERR -v e:/Repos/_misc/Shikanime-vscode-dev-containers:/workspaces/Shikanime-vscode-dev-containers -v C:\Users\clantz\.gitconfig:/root/.gitconfig -l vsch.quality=insider -l vsch.local.folder=e:\Repos\_misc\Shikanime-vscode-dev-containers\containers\kubernetes-helm -l vsch.remote.devPort=9753 -e SYNC_LOCALHOST_KUBECONFIG=true -e SYNC_LOCALHOST_MINIKUBE=true -v /var/run/docker.sock:/var/run/docker.sock -v C:\Users\clantz/.kube:/root/.kube-localhost -v C:\Users\clantz/.minikube:/root/.minikube-localhost vsc-kubernetes-helm-dd44da4c8b378d7c80b16632d4be9982 /bin/sh -c echo Container started ;  while sleep 1; do :; done
``` 

I'm not aware of a way to volume mount conditionally -- I also don't think you can run a local command during the Dockerfile build to create the directory.  

Any ideas?

**Comment by Shikanime** [comment]
@Chuxel If I'm right, the error come from fact that we are mounting a non-existent volume on the host to the docker container? I've never had that kind of problem before.

Since the main difference with docker-for(windows|mac) is that it inline the certificate in the kube config, while Minikube reference external file.

**Comment by Chuxel** [comment]
Yeah here's more of the log file - noticed I'd missed the first part that gave the specific problem.
```Dockerfile
Run: docker run -a STDOUT -a STDERR -v e:/Repos/_misc/Shikanime-vscode-dev-containers:/workspaces/Shikanime-vscode-dev-containers -v C:\Users\clantz\.gitconfig:/root/.gitconfig -l vsch.quality=insider -l vsch.local.folder=e:\Repos\_misc\Shikanime-vscode-dev-containers\containers\kubernetes-helm -l vsch.remote.devPort=9753 -e SYNC_LOCALHOST_KUBECONFIG=true -e SYNC_LOCALHOST_MINIKUBE=true -v /var/run/docker.sock:/var/run/docker.sock -v C:\Users\clantz/.kube:/root/.kube-localhost -v C:\Users\clantz/.minikube:/root/.minikube-localhost vsc-kubernetes-helm-dd44da4c8b378d7c80b16632d4be9982 /bin/sh -c echo Container started ;  while sleep 1; do :; done
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Mount denied:
The source path "C:/Users/clantz/.minikube"
doesn't exist and is not known to Docker.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
Failed: Starting the development container
Command failed: C:\Program Files\Docker\Docker\Resources\bin\docker.exe run -a STDOUT -a STDERR -v e:/Repos/_misc/Shikanime-vscode-dev-containers:/workspaces/Shikanime-vscode-dev-containers -v C:\Users\clantz\.gitconfig:/root/.gitconfig -l vsch.quality=insider -l vsch.local.folder=e:\Repos\_misc\Shikanime-vscode-dev-containers\containers\kubernetes-helm -l vsch.remote.devPort=9753 -e SYNC_LOCALHOST_KUBECONFIG=true -e SYNC_LOCALHOST_MINIKUBE=true -v /var/run/docker.sock:/var/run/docker.sock -v C:\Users\clantz/.kube:/root/.kube-localhost -v C:\Users\clantz/.minikube:/root/.minikube-localhost vsc-kubernetes-helm-dd44da4c8b378d7c80b16632d4be9982 /bin/sh -c echo Container started ;  while sleep 1; do :; done
```

The issue is `"Error response from daemon: Mount denied: The source path "C:/Users/clantz/.minikube" doesn't exist and is not known to Docker.`

The actual path passed in is right, and the error is right that the folder doesn't exist.  I've been looking around and haven't find a way to keep going if this happens. @chrimarti This could be evidence of the need for a prebuild script of some sort.

We could potentially have the flag off by default and then include in the README to add the second mount point in this scenario.

**Comment by Shikanime** [comment]
@Chuxel  Deleted my branch oh i accidentally 😅

**Comment by Chuxel** [comment]
@Shikanime Whoops!  I've done that before.  Happy to review another PR if you recreate (unless you can reopen this one once the branch exists again - never tried that myself).

**Comment by chrmarti** [comment]
@Shikanime Looks like you replaced your branch with the master branch here. I see this commit referenced above: https://github.com/microsoft/vscode-dev-containers/commit/3f22a892187ea1969d39f80ac4c8be755d5fb45e

If that's your change, you could cherry-pick it to your current branch (or create a new branch first).

**Pull request closed without merging**
