### PR TITLE
add --init to definitions

### PR DESCRIPTION
**Pull request by joshspicer**
closes: https://github.com/microsoft/vscode-dev-containers/issues/917

### CODE REVIEW

**Comment by Chuxel** [comment]
One note - We'll also need to add the equivalent to docker-compose.yml for those definitions.

```yaml
services:
  app:
    #...
    init: true
```

**Comment by joshspicer** [comment]
I did in some places, and was going to ask you.  Many of the docker-compose definitions have explicit versions at the top, and init was introduced in version 3.7.  https://docs.docker.com/compose/compose-file/compose-file-v3/#init

You see any harm in updating/removing the version for those docker-compose definitions?

**Comment by joshspicer** [comment]
One example is https://github.com/microsoft/vscode-dev-containers/blob/main/containers/javascript-node-postgres/.devcontainer/docker-compose.yml pinned at version 3.0

**Comment by Chuxel** [comment]
I think `3` is interpreted as `3.x` -- so `3.9`.   You'd need to use `3.0` to pin to that version.  (The only place this wasn't happening in the old version of docker-compose.) That said, I think it's fine to pin to a recent Docker Compose version.

**Comment by joshspicer** [comment]
> I think `3` is interpreted as `3.x` -- so `3.9`.

I'd assumed that too, but the docs say differently: 
https://docs.docker.com/compose/compose-file/compose-versioning/#v2-and-v3-declaration

"When specifying the Compose file version to use, make sure to specify both the major and minor numbers. If no minor version is given, 0 is used by default and not the latest minor version."

**Comment by Chuxel** [comment]
Interesting, then,  yeah, we probably should pick a later version.

**Comment by chrmarti** [comment]
Shouldn't we add this to the extension instead of adding it to all definitions?

**Comment by Chuxel** [comment]
@chrmarti Very happy to do so as I commented here https://github.com/microsoft/vscode-dev-containers/issues/917#issuecomment-919383191.  Do we want to make that the plan?  If so, I'm good with it.

**Comment by chrmarti** [comment]
We could add it automatically if `overrideCommand` is not false to give the user some control. What do you think?

**Comment by Chuxel** [comment]
@chrmarti Yeah it sort of needs to be its own property.  The challenge is that if you want to use systemd, you can't have this enabled since you have to be PID 0.  We have `runArgs` for when we need to add it ad-hoc, but with features we'll need some way of enabling it.

**Comment by eitsupi** [comment]
Hello. It looks like `--init` hasn't been added to some definitions, is this intentional?

**Comment by joshspicer** [comment]
@eitsupi - which definition are you referring to? There are a couple I don't think i updated for various reasons, and also some I may have missed.

**Comment by eitsupi** [comment]
@joshspicer I've noticed R (I was paying attention because I am contributing) and Julia as far as I can see from the container list.
But I don't fully understand the need for `--init`, so it may not be the case.

**Comment by joshspicer** [comment]
The intention of these changes was just as a performance optimization (since most of the time these containers are intended to be long-running processes). Looks like there was no reason to exclude these two - so adding the line in.  Thanks!

**Pull request merged**
