### PR TITLE
config.js file info

### PR DESCRIPTION
**Pull request by LavaAdventures**
File path and file name

### CODE REVIEW

**Comment by Chuxel** [comment]
Thanks for the PR.  However, what does doing this enable?  Why just this file?

**Comment by LavaAdventures** [comment]
It shows what file is being edited.

**Comment by Chuxel** [comment]
@LavaAdventures There are many other ways to find that other than adding it to every file in this repository. Some files do not have header contents either. When would this be useful?

**Comment by Kir-Antipov** [comment]
@Chuxel, don't waste your time, it's Shitoberfest's spammer. Just close this PR.

**Pull request closed without merging**
