### PR TITLE
Update go version in the terraform azure provider

### PR DESCRIPTION
**Pull request by LauraDamianTNA**
Update to go version 1.16, fixes https://github.com/terraform-providers/terraform-provider-azurerm/issues/11048

### CODE REVIEW

**Comment by Chuxel** [comment]
@lawrencegripper Can you review given you'd originally contributed the repository container?

**Comment by lawrencegripper** [comment]
Sorry slow on the response here. Looks good to me.

Added bonus there are 2 go packages that could be updated too. Below I've updated the gopls version from 0.4 -> 0.6.6 and dlv from 1.4.1 -> 1.6.0

```
# Install Go tools
RUN \
    # --> Delve for debugging
    go get github.com/go-delve/delve/cmd/dlv@v1.6.0 \
    # --> Go language server
    && go get golang.org/x/tools/gopls@v0.6.6 \
....
 ```

**Comment by 2percentsilk** [comment]
@lawrencegripper do you want these changes to be part of this PR or would you prefer to make those separately?

**Comment by lawrencegripper** [comment]
Happy for them to go separately, this is a useful fix in it's own right.

**Pull request merged**
