### PR TITLE
removes set echo from dotnet-mssql

### PR DESCRIPTION
**Pull request by dzsquared**
It was unecessary and throwing a visible error in the container creation log

https://github.com/microsoft/vscode-dev-containers/issues/754

secondary - fixing a residual mistake in the test project

### CODE REVIEW

**Comment by bamurtaugh** [comment]
Thanks for updating @dzsquared! The changes make sense to me.

I had a couple of other questions as I checked out this definition:

1. I ran a .NET Restore, but I'm still receiving the following problems - did I miss a step? 
image

I'm still able to run the app.

2. Should we update the guidance in the README? I notice the following:

> 6. After packages are restored, press <kbd>F5</kbd> to start the project.
> 7. Once the project is running, press <kbd>F1</kbd> and select **Remote-Containers: Forward Port from Container...**
> 8. Select port 8090 and click the "Open Browser" button in the notification that appears.
> 9. You should see "Hello remote world from ASP.NET Core!" after the page loads.

When I ran this project with the Program.cs in test-project, an F5 autoforwards the port 8090, and opening port 8090 brings me to the following (I can also see where in Program.cs, it's set to print out "The databases are..." rather than "Hello remote world from ASP.NET Core!"):

image

**Comment by Chuxel** [comment]
@dzsquared - Gentle ping on @bamurtaugh 's questions.  Thanks!

**Comment by bamurtaugh** [comment]
Thanks for re-pinging, @Chuxel! 

@dzsquared Please let me know when this one is ready for review again, and I'll be happy to look it over. 😄

**Comment by dzsquared** [comment]
@bamurtaugh - I **finally** got back into this.  
Made the adjustments/corrections to the README as you noted, thank you!

I also saw the intellisense issue and in troubleshooting it, I bumped the devcontainer to netcore 5 and MDS 3 to match the primary dotnet devcontainer.  Magically, intellisense is now functioning correctly when I build the devcontainer.

thank you!

**Comment by bamurtaugh** [comment]
Thanks for the updates @dzsquared! The readme looks great and matches the experience when I tested the app. My question remains with the IntelliSense/problems that pop up - it looks like I'm still experiencing the same red underlines, any ideas?

image

**Comment by dzsquared** [comment]
@bamurtaugh - as to the intellisense issue with .NET in VS Code I'm not sure of the cause or a definitive fix.  I was able to repro it until I bumped the dev container to netcore 5 and MDS 3.

**Comment by bamurtaugh** [comment]
Thanks for looking into it! Would you be able to resolve the merge conflict so that we can do a final merge?

**Comment by dzsquared** [comment]
done, thanks!

**Review by bamurtaugh — APPROVED** [review]
LGTM, thanks @dzsquared!

**Pull request merged**
