### PR TITLE
Added default mount for Ansible Collections

### PR DESCRIPTION
**Pull request by cmendible**
Added default mount for Ansible Collections. Solving #368

### CODE REVIEW

**Comment by Chuxel** [comment]
The only downside here is that the container does not start if the path that is mounted is not present. One way to resolve that would be to have the mount commented out.  Another could be to have a couple of scripts that create the directory if it doesn't exist that are referenced from `initializeCommand`.  (You'd could name one `create-ansible-dir` with the execute bit set for linix/macOS and another `create-ansible-dir.cmd` for windows.)

**Comment by cmendible** [comment]
> The only downside here is that the container does not start if the path that is mounted is not present. One way to resolve that would be to have the mount commented out. Another could be to have a couple of scripts that create the directory if it doesn't exist that are referenced from `initializeCommand`. (You'd could name one `create-ansible-dir` with the execute bit set for linix/macOS and another `create-ansible-dir.cmd` for windows.)

I swear I tested that behavior on my windows box and the local folder does get created. I'll try again and come back to you with the results.

**Comment by cmendible** [comment]
> The only downside here is that the container does not start if the path that is mounted is not present. One way to resolve that would be to have the mount commented out. Another could be to have a couple of scripts that create the directory if it doesn't exist that are referenced from `initializeCommand`. (You'd could name one `create-ansible-dir` with the execute bit set for linix/macOS and another `create-ansible-dir.cmd` for windows.)

I commented out the mount as optional.

**Comment by Chuxel** [comment]
LGTM!

**Pull request merged**
