### PR TITLE
[codespaces] bump oryx 20210308.3

### PR DESCRIPTION
**Pull request by joshspicer**
Bumps oryx to latest vso-focal build.  Also changes how we symlink dotnet to dynamically accept the versions included with oryx.

Tested with vscode dev containers locally.

Have not validated that this oryx build fixes the python issues we are seeing.  I think the easiest way to validate _that_ is to get this merged and use the generated dev image to validate - right @Chuxel ?

### CODE REVIEW

**Comment by Chuxel** [comment]
@joshspicer You can also just copy the `.devcontainer` folder into a repo, update devcontainer.json to point to "base.Dockerfile", and open it in a codespace.  It takes a long time because of how huge the image is, but it works. The devcontianer.json calls `oryx build` as postCreateCommand... you can also call it manually of course.

**Comment by joshspicer** [comment]
ah yes, running the post-create manually makes sense :)

**Comment by Chuxel** [comment]
@joshspicer LGTM! Should we merge it or do you want to do more checking?

**Comment by Chuxel** [comment]
I'm going to merge this in since it looks good and I need to push an update to fix a bug anyway.

**Pull request merged**
