### PR TITLE
add fish-debian.sh as a feature

### LINKED ISSUE #1230: Add `fish-debian.sh` as a feature
Is it possible to add this script as a feature in order to install fish in the container?
It looks like only `fish-debian.sh` is not registered as a feature in the script for Debian.

Relates to: Both

### PR DESCRIPTION
**Pull request by eitsupi**
close #1230

I have made minimal edits with reference to other scripts, but please let me know if I have misunderstood something.

cc @andreiborisov

### CODE REVIEW

**Comment by andreiborisov** [comment]
@eitsupi looks good to me🙌🏻

**Comment by eitsupi** [comment]
@Chuxel Can you please review it? It seems to have passed the features' test.

**Comment by Chuxel** [comment]
Took a quick look.  It's probably worth checking for curl, ca-certificates, apt-transport-https, and gnupg2. Running the script with the base "debian" image results in the following error:

```
#7 0.612 Installing fish shell...
#7 0.618 deb http://download.opensuse.org/repositories/shells:/fish/Debian_11/ /
#7 0.619 /script-library/fish-debian.sh: line 59: curl: command not found
#7 0.619 /script-library/fish-debian.sh: line 59: gpg: command not found
```

**Comment by eitsupi** [comment]
Thanks for the feedback, I was only thinking of the common script executed image.
I will make the change to add the necessary packages.

**Comment by eitsupi** [comment]
Changed to work with `debian:latest` and `ubuntu:latest`.
It seems to pass the test too.

**Comment by Chuxel** [comment]
LGTM!!

**Comment by andreiborisov** [comment]
@eitsupi doesn’t seem to work when building Codespaces dev container, is it live yet?

**Comment by eitsupi** [comment]
@andreiborisov I just set up featuers on a `ubuntu:focal` base container and verified that fish is installed successfully.
I don't know why yours didn't work there as I don't have the rights to use CodeSpaces...

**Comment by andreiborisov** [comment]
@eitsupi ok, thanks for the confirmation and the contribution🚀, I’ll try to look into it.

**Pull request merged**
