### PR TITLE
update install.sh

### PR DESCRIPTION
**Pull request by joshspicer**
Update to work with https://github.com/microsoft/vscode-remote-containers/pull/153

### CODE REVIEW

**Comment by Chuxel** [comment]
Does the Dockerfile need to get updated too for the copy statement?

**Comment by joshspicer** [comment]
This dockerfile won't be used anymore, I now keep it here:
https://github.com/joshspicer/vscode-remote-containers/blob/4f3126aa0832c55bfb04c793971d2b853b83611c/src/configuration/containerFeaturesConfiguration.ts#L55

**Comment by joshspicer** [comment]
I suppose for clarity, i'll delete that Dockerfile

**Comment by Chuxel** [comment]
Can we still regression test?  The Dockerfile in this repo was there to allow us to run a test.sh to verify the script is working as things change.  We can wire that into CI.  Using the test script and test.sh right now.

**Comment by joshspicer** [comment]
ah yes, will fix that up.

**Comment by joshspicer** [comment]
Added new CI job to run that test.sh

**Comment by Chuxel** [comment]
LGTM!! Merge when ready!

**Pull request merged**
