### PR TITLE
Update rust-debian.sh

### PR DESCRIPTION
**Pull request by Rose2161**

### CODE REVIEW

**Comment by Chuxel** [comment]
This appears to be spam.

**Comment by Rose2161** [comment]
No it's not

Aisha Redl-Sherwood, CEO/CFO
503-857-9072
Cryptob3auty I.S.
P.O. Box 1524
McMinnville, Or 97128

**Comment by Rose2161** [comment]
No it's not spam!

**Comment by Chuxel** [comment]
The net effect here would be to update the user in the script which is not something we'd want to do. The script will automatically detect whatever user has a UID/GID of 1000 in the image if one already exists and the other names are not present.

**Pull request closed without merging**
