### PR TITLE
Add R devcontainer for statistical computing

### PR DESCRIPTION
**Pull request by kmehant**
# Context
We can have `R devcontainer` added to the present vs code development container ecosystem.

### CODE REVIEW

**Comment by kmehant** [comment]
Hello @Chuxel 
We are missing a debugging extension for R so how should we be proceeding with `launch.json` and the `devcontainer`  itself.

**Comment by Chuxel** [comment]
@kmehant Thanks for the PR!  A few comments:

1. One of these extensions appears to require .NET Core which needs to be installed in the `Dockerfile`. Unfortunately, the R image uses the unreleased Debian buster which makes that tricky to do.
2. Is there a reason to install both extensions?

**Comment by kmehant** [comment]
> @kmehant Thanks for the PR! A few comments:
> 
> 1. One of these extensions appears to require .NET Core which needs to be installed in the `Dockerfile`. Unfortunately, the R image uses the unreleased Debian buster which makes that tricky to do.
> 2. Is there a reason to install both extensions?

@Chuxel Thanks for the valuable review! Let me remove **R Tools** extension for now as the other extension satisfies the basic needs (syntax, snippet and run) for programming in R.

**Comment by Chuxel** [comment]
> Thanks for the valuable review! Let me remove R Tools extension for now as the other extension satisfies the basic needs (syntax, snippet and run) for programming in R and will update the readme more aptly to the development 😄

I expect people will want to use the other extension give it provides more features, so ideally we'd figure out how to get .NET Core into the container so it can be used.

**Comment by kmehant** [comment]
@Chuxel I have used **R base image** which is built on top of **Ubuntu:bionic** and installed **.NET core runtime 2.1** and **libzip** as dependencies for **R Tools** extension.

**Comment by kmehant** [comment]
@Chuxel  Can we get this merged 😃?

**Comment by Chuxel** [comment]
LGTM!

**Pull request merged**
