### PR TITLE
Update oryx version and definition file for codespaces-linux

### PR DESCRIPTION
**Pull request by edgonmsft**

### CODE REVIEW

**Comment by edgonmsft** [comment]
@Chuxel We have one more update to a newer oryx image that fixes PHP on the path. Just finished testing.

Thanks!

**Comment by dmgardiner25** [comment]
@edgonmsft Do we want to remove PHP from the `EXTRA_PATHS` variable in the image since it is included in the new Oryx image?

**Comment by edgonmsft** [comment]
Yep, done.

**Comment by Chuxel** [comment]
Doing a local sanity test real quick.  Is this something you want released ASAP?

**Comment by edgonmsft** [comment]
@Chuxel Thanks a lot! 

Yes if possible.

**Comment by Chuxel** [comment]
@edgonmsft  I'm seeing the following warning when building Git from source.  Is this of any concern?
````
/usr/bin/ld: warning: libssl.so.1.0.2, needed by /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.so, may conflict with libssl.so.1.1
/usr/bin/ld: warning: libcrypto.so.1.0.2, needed by /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libcurl.so, may conflict with libcrypto.so.1.1
```
Not sure if that is new or not.  Otherwise LGTM.

**Comment by edgonmsft** [comment]
I saw them too but not sure. I tested git inside the container and seems to be working fine.

**Comment by Chuxel** [comment]
Once CI runs successfully, I can cut a 0.122 release so the update for this definition goes out.  Looks like this should also fix https://github.com/microsoft/vscode-dev-containers/issues/322

**Pull request merged**
