### PR TITLE
feat(javascript-node-14): update definition for Node 14

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This changes details of the base `javascript-node-*` template to add
support for Node 14. That way, if accepted, other depending templates
could be updated, if relying on that base image

No specific changes compared to v12 were made.
The 'forwardPorts' option
is left-as-is, as it's documented in the template README

Thanks!

Test output:
```bash
# ./test.sh 
🧪 Testing vscode-server: [ 1 -ge 1 ] 🏆 Passed!
🧪 Testing dbaeumer.vscode-eslint: [ 1 -ge 1 ] 🏆 Passed!
🧪 Testing node: node --version v14.1.0 🏆 Passed!
🧪 Testing non-root-user: id node uid=1000(node) gid=1000(node) groups=1000(node) 🏆 Passed!
🧪 Testing /home/node: [ -d /home/node ] 🏆 Passed!
🧪 Testing sudo: sudo -u node echo sudo works. sudo works. 🏆 Passed!
🧪 Testing git: git --version git version 2.11.0 🏆 Passed!
🧪 Testing command-line-tools: which top ip lsb_release /usr/bin/top /sbin/ip /usr/bin/lsb_release 🏆 Passed!
🧪 Testing yarn: yarn install yarn install v1.22.4 warning package.json: No license fieldwarning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json. warning docker_web_app@1.0.0: No license field [1/4] Resolving packages... [2/4] Fetching packages... [3/4] Linking dependencies... [4/4] Building fresh packages... Done in 3.32s. 🏆 Passed!
🧪 Testing npm: npm install npm WARN docker_web_app@1.0.0 No repository field. npm WARN docker_web_app@1.0.0 No license field. removed 4 packages, updated 48 packages and audited 121 packages in 5.222s found 0 vulnerabilities 🏆 Passed!
🧪 Testing eslint: eslint server.js 🏆 Passed!
🧪 Testing test-project: npm run test > docker_web_app@1.0.0 test /workspaces/vscode-dev-containers/containers/javascript-node-14/test-project > REGRESSION_TESTING=true npm start > docker_web_app@1.0.0 start /workspaces/vscode-dev-containers/containers/javascript-node-14/test-project > node server.js Running on http://0.0.0.0:3000 🏆 Passed!
💯 All passed! 
```

Container logs:
```bash
{
	"Id": "653cd872990e98f8593b53dcc82c160b2f25dc77c0e97f6dde04686b7ef8c38f",
	"Created": "2020-05-03T09:39:06.383266358Z",
	"Path": "/bin/sh",
	"Args": [
		"-c",
		"echo Container started ; while sleep 1; do :; done"
	],
	"State": {
		"Status": "running",
		"Running": true,
		"Paused": false,
		"Restarting": false,
		"OOMKilled": false,
		"Dead": false,
		"Pid": 5321,
		"ExitCode": 0,
		"Error": "",
		"StartedAt": "2020-05-03T09:44:29.993161008Z",
		"FinishedAt": "2020-05-03T09:43:56.036494085Z"
	},
	"Image": "sha256:dcc9a6c21de0c9c6c3725e6f663084b191005cabc16f8bcb8cf373af2571af44",
	"ResolvConfPath": "/var/lib/docker/containers/653cd872990e98f8593b53dcc82c160b2f25dc77c0e97f6dde04686b7ef8c38f/resolv.conf",
	"HostnamePath": "/var/lib/docker/containers/653cd872990e98f8593b53dcc82c160b2f25dc77c0e97f6dde04686b7ef8c38f/hostname",
	"HostsPath": "/var/lib/docker/containers/653cd872990e98f8593b53dcc82c160b2f25dc77c0e97f6dde04686b7ef8c38f/hosts",
	"LogPath": "/var/lib/docker/containers/653cd872990e98f8593b53dcc82c160b2f25dc77c0e97f6dde04686b7ef8c38f/653cd872990e98f8593b53dcc82c160b2f25dc77c0e97f6dde04686b7ef8c38f-json.log",
	"Name": "/funny_jennings",
	"RestartCount": 0,
	"Driver": "overlay2",
	"Platform": "linux",
	"MountLabel": "",
	"ProcessLabel": "",
	"AppArmorProfile": "",
	"ExecIDs": [
		"8c3b7c5605628df4994060d47b2c32a0f68df7a4a2a62f849f5f5a5c2b8526d5",
		"cb64fe5b9801bd2fbffc24f5ff101470d7972b9bc3c5cadeb7a376a972caf1d3",
		"811644998da0f7a86bf3e45e31ee77e0dfc07b93cfec9859b6458a68a86af9ec",
		"d6b021e610f006343038d291f2e48c67b76304e4bf4ca046a56839e33dcb50f2",
		"482c4b6e508c495891df1f0858d772649c5817fe8264814c3624a6ca72c7faf0",
		"62f3d281590831b2f6f73931dd0bce212f958c699d4a42c5e944e512b651f209",
		"2e00dedea72b3dfd4a09a37ff189aa561bdd81a083056dff5860a0c0c19dfd30",
		"9fea206daa438de70911b84e5542a75929bd4f7664afce3a709b18584d7dca97",
		"c9e0c9191442a6c46e6dff5ce5c5abaac826c54a610e25276180220d400ee623"
	],
	"HostConfig": {
		"Binds": null,
		"ContainerIDFile": "",
		"LogConfig": {
			"Type": "json-file",
			"Config": {}
		},
		"NetworkMode": "default",
		"PortBindings": {},
		"RestartPolicy": {
			"Name": "no",
			"MaximumRetryCount": 0
		},
		"AutoRemove": false,
		"VolumeDriver": "",
		"VolumesFrom": null,
		"CapAdd": null,
		"CapDrop": null,
		"Capabilities": null,
		"Dns": [],
		"DnsOptions": [],
		"DnsSearch": [],
		"ExtraHosts": null,
		"GroupAdd": null,
		"IpcMode": "private",
		"Cgroup": "",
		"Links": null,
		"OomScoreAdj": 0,
		"PidMode": "",
		"Privileged": false,
		"PublishAllPorts": false,
		"ReadonlyRootfs": false,
		"SecurityOpt": null,
		"UTSMode": "",
		"UsernsMode": "",
		"ShmSize": 67108864,
		"Runtime": "runc",
		"ConsoleSize": [
			24,
			80
		],
		"Isolation": "",
		"CpuShares": 0,
		"Memory": 0,
		"NanoCpus": 0,
		"CgroupParent": "",
		"BlkioWeight": 0,
		"BlkioWeightDevice": [],
		"BlkioDeviceReadBps": null,
		"BlkioDeviceWriteBps": null,
		"BlkioDeviceReadIOps": null,
		"BlkioDeviceWriteIOps": null,
		"CpuPeriod": 0,
		"CpuQuota": 0,
		"CpuRealtimePeriod": 0,
		"CpuRealtimeRuntime": 0,
		"CpusetCpus": "",
		"CpusetMems": "",
		"Devices": [],
		"DeviceCgroupRules": null,
		"DeviceRequests": null,
		"KernelMemory": 0,
		"KernelMemoryTCP": 0,
		"MemoryReservation": 0,
		"MemorySwap": 0,
		"MemorySwappiness": null,
		"OomKillDisable": false,
		"PidsLimit": null,
		"Ulimits": null,
		"CpuCount": 0,
		"CpuPercent": 0,
		"IOMaximumIOps": 0,
		"IOMaximumBandwidth": 0,
		"Mounts": [
			{
				"Type": "bind",
				"Source": "/host_mnt/c/development/vscode-dev-containers",
				"Target": "/workspaces/vscode-dev-containers",
				"Consistency": "cached"
			}
		],
		"MaskedPaths": [
			"/proc/asound",
			"/proc/acpi",
			"/proc/kcore",
			"/proc/keys",
			"/proc/latency_stats",
			"/proc/timer_list",
			"/proc/timer_stats",
			"/proc/sched_debug",
			"/proc/scsi",
			"/sys/firmware"
		],
		"ReadonlyPaths": [
			"/proc/bus",
			"/proc/fs",
			"/proc/irq",
			"/proc/sys",
			"/proc/sysrq-trigger"
		]
	},
	"GraphDriver": {
		"Data": {
			"LowerDir": "/var/lib/docker/overlay2/84d25ba65ccb7cd2c8582e873ea7487de5debf22b1061ce35bea83aded79c338-init/diff:/var/lib/docker/overlay2/7b7e2938c6e4800c1a3310790e0142ea6ffbf8e77620246c8ac73f8f1edb69f6/diff:/var/lib/docker/overlay2/eb1e44372fce51b26d6d51c6b0b4fb26f033a163234f57e1b15a90b0e66bf021/diff:/var/lib/docker/overlay2/838003980eba0e86470803e12518c62f68cf09986ad5d1361281b89461eba63a/diff:/var/lib/docker/overlay2/6dfac8a669e8cf7bb25dc801e6b754e466b15735864e3e5022506e3744fde7b6/diff:/var/lib/docker/overlay2/49cf9948ca05f6178fc6fe560f541cec9f99fc26a62426f3f2ae13dd7b40a0dd/diff:/var/lib/docker/overlay2/d41fb66fc8eb1d55c9b12f0f5c095c85ecdae2cc170d0e691f26e7db7aaba76b/diff:/var/lib/docker/overlay2/d3dacadfb117c52829e91995e1b68e58800e525b1f0703daea35575ab5b5b0aa/diff:/var/lib/docker/overlay2/975387ac211a51dbe18b504f124572cf479824a883b863cd81c8d5cf90341f9a/diff:/var/lib/docker/overlay2/251b8a83683d1e26f661ad0dd196039756f3f3190b475e4c7e04eb78d08af27a/diff:/var/lib/docker/overlay2/aa032055fbb753de8ffe148c8d7e3d5277aee834cc521e1d4a3822f6f4d00076/diff",
			"MergedDir": "/var/lib/docker/overlay2/84d25ba65ccb7cd2c8582e873ea7487de5debf22b1061ce35bea83aded79c338/merged",
			"UpperDir": "/var/lib/docker/overlay2/84d25ba65ccb7cd2c8582e873ea7487de5debf22b1061ce35bea83aded79c338/diff",
			"WorkDir": "/var/lib/docker/overlay2/84d25ba65ccb7cd2c8582e873ea7487de5debf22b1061ce35bea83aded79c338/work"
		},
		"Name": "overlay2"
	},
	"Mounts": [
		{
			"Type": "bind",
			"Source": "/host_mnt/c/development/vscode-dev-containers",
			"Destination": "/workspaces/vscode-dev-containers",
			"Mode": "",
			"RW": true,
			"Propagation": "rprivate"
		}
	],
	"Config": {
		"Hostname": "653cd872990e",
		"Domainname": "",
		"User": "",
		"AttachStdin": false,
		"AttachStdout": true,
		"AttachStderr": true,
		"Tty": false,
		"OpenStdin": false,
		"StdinOnce": false,
		"Env": [
			"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/share/npm-global/bin",
			"NODE_VERSION=14.1.0",
			"YARN_VERSION=1.22.4",
			"DEBIAN_FRONTEND=dialog"
		],
		"Cmd": [
			"-c",
			"echo Container started ; while sleep 1; do :; done"
		],
		"Image": "vsc-javascript-node-14-794674cdd7dc7fe6de5e82dcce525fc2",
		"Volumes": null,
		"WorkingDir": "",
		"Entrypoint": [
			"/bin/sh"
		],
		"OnBuild": null,
		"Labels": {
			"vsch.local.folder": "c:\\development\\vscode-dev-containers\\containers\\javascript-node-14",
			"vsch.quality": "stable",
			"vsch.remote.devPort": "0"
		}
	},
	"NetworkSettings": {
		"Bridge": "",
		"SandboxID": "6ceb0025aeef102b9c646ffdc7a919c33a3f33d23a23ac87846c2a20d0a06b88",
		"HairpinMode": false,
		"LinkLocalIPv6Address": "",
		"LinkLocalIPv6PrefixLen": 0,
		"Ports": {},
		"SandboxKey": "/var/run/docker/netns/6ceb0025aeef",
		"SecondaryIPAddresses": null,
		"SecondaryIPv6Addresses": null,
		"EndpointID": "d8e21344165b524cbe7ad243f5c7b763433c098cbb60c1631093af18bba1e3e8",
		"Gateway": "172.17.0.1",
		"GlobalIPv6Address": "",
		"GlobalIPv6PrefixLen": 0,
		"IPAddress": "172.17.0.2",
		"IPPrefixLen": 16,
		"IPv6Gateway": "",
		"MacAddress": "02:42:ac:11:00:02",
		"Networks": {
			"bridge": {
				"IPAMConfig": null,
				"Links": null,
				"Aliases": null,
				"NetworkID": "7eef4fce616b8ffa52137153abc76b25f08e699b800444d1b19d88761fdcfb72",
				"EndpointID": "d8e21344165b524cbe7ad243f5c7b763433c098cbb60c1631093af18bba1e3e8",
				"Gateway": "172.17.0.1",
				"IPAddress": "172.17.0.2",
				"IPPrefixLen": 16,
				"IPv6Gateway": "",
				"GlobalIPv6Address": "",
				"GlobalIPv6PrefixLen": 0,
				"MacAddress": "02:42:ac:11:00:02",
				"DriverOpts": null
			}
		}
	},
	"Ports": []
}
```

### CODE REVIEW

**Comment by Chuxel** [comment]
LGTM!

**Comment by peterblazejewicz** [comment]
@Chuxel marvelous!
What's the correct approach now (or next steps)? Should I wait with other templates (javascript/typescript/darp) until the relevant docker image tag appears in the registry?
Thanks!

**Comment by Chuxel** [comment]
@peterblazejewicz If you'd like to update those as well, great!  There is a "dev" tag that is released with the merge into master that should be available now for testing.

`mcr.microsoft.com/vscode/devcontainers/javascript-node:dev-14`

Next release that gets cut out of this repo will publish the non-`dev` version.

**Comment by peterblazejewicz** [comment]
Thanks, appreciate response!

**Pull request merged**
