### PR TITLE
Make sure to run Homebrew as a non-root user only

### PR DESCRIPTION
**Pull request by andreiborisov**
Fixes: https://github.com/microsoft/vscode-dev-containers/issues/1490

### CODE REVIEW

**Comment by bamurtaugh** [comment]
Thanks @andreiborisov!

@joshspicer it looks like some tests didn't pass this PR - is that a concern?

**Comment by andreiborisov** [comment]
I need to look into this again, it seems like there is an issue upstream that need to be fixed first

**Comment by joshspicer** [comment]
Thanks, @andreiborisov!

**Comment by andreiborisov** [comment]
@Michaelvsk we migrated Homebrew installation script on the Devcontainer Features spec. Please, use the new feature: https://github.com/meaningful-ooo/devcontainer-features/tree/main/src/homebrew

**Pull request closed without merging**
