### PR TITLE
Create a container definition for JavaScript exercism.io (Node 12)

### PR DESCRIPTION
**Pull request by CyberLight**
This change creates a container definition for Javascript [exercism.io](https://exercism.io/) task solving environment based on Node.js 12

### CODE REVIEW

**Comment by bamurtaugh** [comment]
Thanks for tagging me. I agree with raising awareness from the Exercism docs and/or extension. I did notice the extension appears not to be officially associated with Exercism, though.

I also wonder where it makes the most sense for this container definition to live- it seems like individuals who would like to use it might get the most benefit from it if it could be merged directly as part of an Exercism repo (maybe going one step beyond just referencing it there). Is there a location from which users pull Exercism exercises? It feels like it'd be natural to include a dev container definition there, so that they could pull source code + a dev container all together.

I also agree with Chuck's comments about making the definition as general as possible.

**Comment by CyberLight** [comment]
@Chuxel and @bamurtaugh you are right, earlier I thought that will be nice if this container would be in the VSCode container repository, because it already contains all the necessary tools in order not to look somewhere in the documentation or elsewhere, but you convinced me that it is easier for everyone to create such a container by himself using VSCode Remote Containers.

Alas, I could not write my nickname in history :)

I think that this MR can be closed, but I got experience while creating this container, this is an invaluable experience. Thank you for your time, you are the best!

**Comment by Chuxel** [comment]
Sounds good!  Thanks for the work on it!

**Comment by bamurtaugh** [comment]
Thank you for your time and work in creating this container definition! Glad it could be a good experience :)

**Pull request closed without merging**
